### PR TITLE
Create openapi.yaml

### PR DESCRIPTION
**Pull request by ravinduheshanweerasinghe**
Part of: [#7041](https://github.com/ballerina-platform/ballerina-library/issues/7041)

## Examples
N/A

## Checklist
- [X] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [x] Updated the spec
- [ ] Checked native-image compatibility

### CODE REVIEW

**Comment by ravinduheshanweerasinghe** [comment]
Can you please check whether added openapi.yaml file correct or not. And please guide me to how to find null schemas in openapi.yaml file and how to fix them.

**Comment by ayeshLK** [comment]
@ravinduheshanweerasinghe I see that you have updated the `sanitations.md`. Have we done any sanitations to the official openapi.yaml ? If not let's remove those changes for now.

**Comment by ayeshLK** [comment]
@ravinduheshanweerasinghe since SendGrid has multiple API endpoints, during this effort we will focus only on SendGrid Email [1] API. So, we need to add the official OpenAPI spec for that in this PR.

[1] - https://github.com/twilio/sendgrid-oai/blob/main/spec/json/tsg_mail_v3.json

**Comment by ayeshLK** [comment]
Since there is no any progress on this PR we will close it for now.

**Pull request closed without merging**
